import { useSyncExternalStore } from "react";
import { z } from "zod";
import {
  AddressSchema,
  BuildingSchema,
  RecommendationSchema,
  type Address,
  type Building,
  type Recommendation,
  type UsageProfile,
} from "../schemas/sizing";
import { ApiError, api, isApiReachable, loadDemoFallback } from "./client";

/**
 * ARCHITECTURE.md 9.3 — the demo fallback, wired into the flow.
 *
 *     "If external geocoding or imagery fails, the web app still demonstrates
 *      the full Bill-to-Roof calculation from its local pilot data."
 *
 * Every screen calls `dataSource` rather than `api`. While the API answers, the
 * two are the same thing. When it stops answering, this module switches to the
 * bundle generated by `backend/scripts/build_demo_fallback.py` and says so out
 * loud, because an offline result is a different claim from a live one.
 *
 * What it will NOT do:
 *
 *   * Compute anything. The optimiser, the tariff engine and the subsidy rules
 *     live on the server and stay there. Offline, this module can only serve a
 *     result the real engine already produced for a stored household profile —
 *     so it never pretends the household's own bill was used.
 *   * Hide a bug. A 4xx is the API answering, and a Zod failure is a schema
 *     drift ARCHITECTURE.md 8 wants loud. Neither triggers a fallback.
 */

export type DataMode = "LIVE" | "FALLBACK";

export interface DataState {
  mode: DataMode;
  /** Why we fell back, in a sentence fit to show a household. */
  reason: string | null;
}

/** The bundle holds a roof but no sizing result for it — PRD 11's VIT case. */
export class NoStoredResultError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "NoStoredResultError";
  }
}

/** The API is down AND the bundled pilot data could not be read. */
export class FallbackUnavailableError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "FallbackUnavailableError";
  }
}

/* -- store ---------------------------------------------------------------- */

let state: DataState = { mode: "LIVE", reason: null };
const listeners = new Set<() => void>();

function set(next: DataState): void {
  if (next.mode === state.mode && next.reason === state.reason) return;
  state = next;
  for (const listener of listeners) listener();
}

export function getDataState(): DataState {
  return state;
}

function subscribe(listener: () => void): () => void {
  listeners.add(listener);
  return () => {
    listeners.delete(listener);
  };
}

/** Subscribe a component to live/fallback changes. */
export function useDataState(): DataState {
  return useSyncExternalStore(subscribe, getDataState, getDataState);
}

/* -- the bundle ----------------------------------------------------------- */

/**
 * Parsed with the same schemas the live responses are parsed with. The bundle
 * is generated from the API's own serialisers, so if it fails here it is stale
 * — and a loud failure beats a screen of blank panels.
 */
const BundleSchema = z.object({
  _grid_disclosure: z.string().min(1),
  addresses: AddressSchema.array(),
  buildings: z.record(BuildingSchema),
  recommendations: z.record(RecommendationSchema),
});

type Bundle = z.infer<typeof BundleSchema>;

let bundlePromise: Promise<Bundle> | null = null;

function bundle(): Promise<Bundle> {
  bundlePromise ??= loadDemoFallback()
    .then((raw) => BundleSchema.parse(raw))
    .catch((err) => {
      bundlePromise = null; // a retry should be allowed to succeed
      throw err;
    });
  return bundlePromise;
}

/* -- outage detection ------------------------------------------------------ */

/** 502/503/504 is infrastructure. 500 is our bug, and must not be papered over. */
const OUTAGE_STATUSES = new Set([502, 503, 504]);

function outageReason(err: unknown): string | null {
  if (err instanceof ApiError) {
    return OUTAGE_STATUSES.has(err.status)
      ? `The sizing service answered ${err.status}.`
      : null;
  }
  const name = (err as { name?: string } | null)?.name;
  if (name === "TimeoutError" || name === "AbortError") {
    return "The sizing service did not answer in time.";
  }
  // fetch() rejects with a TypeError for DNS, connection-refused and CORS
  // failures alike — the browser deliberately does not say which.
  if (err instanceof TypeError) {
    return "The browser could not reach the sizing service.";
  }
  return null;
}

const SEARCH_MS = 3000;
const BUILDING_MS = 4000;
const SIZING_MS = 8000;

function budget(ms: number) {
  return { signal: AbortSignal.timeout(ms) };
}

async function withFallback<T>(
  live: () => Promise<T>,
  offline: (b: Bundle) => T,
): Promise<T> {
  if (state.mode === "LIVE") {
    try {
      return await live();
    } catch (err) {
      const reason = outageReason(err);
      if (!reason) throw err; // a real answer, or a real bug
      set({ mode: "FALLBACK", reason });
    }
  }

  let loaded: Bundle;
  try {
    loaded = await bundle();
  } catch {
    throw new FallbackUnavailableError(
      "The sizing service is unreachable and the bundled pilot data could not be read.",
    );
  }
  return offline(loaded);
}

/**
 * Offline address matching. The live route uses pg_trgm; this is a plain
 * all-terms substring match over five bundled addresses, which is the honest
 * shape of a five-row table. It is deliberately not fuzzy: offline, a near miss
 * should read as "not in the pilot", not as a silent nearest guess.
 */
function matchAddresses(all: Address[], q: string): Address[] {
  const needle = q.trim().toLowerCase();
  if (needle.length < 3) return [];
  const terms = needle.split(/\s+/).filter(Boolean);
  return all.filter((a) => {
    const hay = a.display_name.toLowerCase();
    return terms.every((t) => hay.includes(t));
  });
}

/* -- the source the screens call ------------------------------------------ */

export const dataSource = {
  searchAddresses: (q: string): Promise<Address[]> =>
    withFallback(
      () => api.searchAddresses(q, budget(SEARCH_MS)),
      (b) => matchAddresses(b.addresses, q),
    ),

  getBuilding: (id: string): Promise<Building> =>
    withFallback(
      () => api.getBuilding(id, budget(BUILDING_MS)),
      (b) => {
        const found = b.buildings[id];
        if (!found) {
          throw new NoStoredResultError(
            "That roof is not in the bundled pilot data.",
          );
        }
        return found;
      },
    ),

  /**
   * Live, this runs the optimiser over the household's confirmed profile.
   *
   * Offline it cannot: the optimiser is server-side and reimplementing it in
   * the browser would be a second, unverified engine. What it returns instead
   * is the stored result the real engine produced for this roof under a stored
   * profile. The screens label it as exactly that — see `OfflineResultNotice`.
   */
  createSizingRun: (profile: UsageProfile): Promise<Recommendation> =>
    withFallback(
      () => api.createSizingRun(profile, budget(SIZING_MS)),
      (b) => {
        const stored = b.recommendations[profile.building_id];
        if (!stored) {
          throw new NoStoredResultError(
            "There is no stored offline result for this roof.",
          );
        }
        return stored;
      },
    ),

  /**
   * FR-3.1/3.2. Extraction is server-side OCR with no offline equivalent, and
   * inventing one would be inventing a household's bill. Manual entry is the
   * path that always works, and the form says so when this is unavailable.
   */
  extractBill: (file: File) => api.extractBill(file),
};

/**
 * Health check, used on mount and behind the banner's retry. Restores LIVE when
 * the service comes back, so an outage during setup does not strand the session
 * on stored data for the rest of the demo.
 */
export async function probeApi(): Promise<DataMode> {
  const reachable = await isApiReachable();
  if (reachable) {
    set({ mode: "LIVE", reason: null });
    return "LIVE";
  }
  set({
    mode: "FALLBACK",
    reason: "The sizing service is not answering its health check.",
  });
  return "FALLBACK";
}
